services:
  rocket:
    container_name: "rocket"
    image: rocket
    build:
      context: .
      dockerfile: Rocket/Dockerfile
    environment:
      ROCKET_COMMAND_PATH: ""
      ROCKET_LOG_FILE: ""
      ROCKET_DISCORD_TOKEN: ""
      ROCKET_DYNAMIC_CHANNEL_NAME: ""
#    volumes:
#      - ./logs:/logs:rw
#      - ./configs:/configs:ro
